
// TSYS_MENU
export const TSYS_MENU_ON_GET_LIST = 'TSYS_MENU_ON_GET_LIST';
export const TSYS_MENU_ON_GET_LIST_SUCCESS = 'TSYS_MENU_ON_GET_LIST_SUCCESS'; 
export const TSYS_MENU_ON_GET_LIST_FAILURE = 'TSYS_MENU_ON_GET_LIST_FAILURE';
export const TSYS_MENU_ON_SAVE = 'TSYS_MENU_ON_SAVE';
export const TSYS_MENU_ON_SAVE_SUCCESS = 'TSYS_MENU_ON_SAVE_SUCCESS';
export const TSYS_MENU_ON_SAVE_FAILURE = 'TSYS_MENU_ON_SAVE_FAILURE';
export const TSYS_MENU_ON_SEND = 'TSYS_MENU_ON_SEND';
export const TSYS_MENU_ON_SEND_SUCCESS = 'TSYS_MENU_ON_SEND_SUCCESS';
export const TSYS_MENU_ON_SEND_FAILURE = 'TSYS_MENU_ON_SEND_FAILURE';
export const TSYS_MENU_GET_LIST = 'TSYS_MENU_GET_LIST';
export const TSYS_MENU_GET_LIST_SUCCESS = 'TSYS_MENU_GET_LIST_SUCCESS';
export const TSYS_MENU_GET_LIST_FAILURE = 'TSYS_MENU_GET_LIST_FAILURE';